[package]
name = "alphapulse-market-data-relay"
version = "0.1.0"
edition = "2021"
description = "High-performance market data relay for >1M msg/s throughput"

[dependencies]
# Core relay infrastructure with speed-focused features
alphapulse-relays = { path = "..", features = ["market-data-relay"] }
protocol_v2 = { path = "../../protocol_v2" }

# Async runtime - minimal features for binary
tokio = { version = "1.0", features = ["rt-multi-thread", "net", "io-util", "time", "macros"] }
async-trait = "0.1"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Error handling
anyhow = "1.0"

# Command line
clap = { version = "4.0", features = ["derive"] }

# Utilities
bytes = "1.5"
futures = "0.3"

[[bin]]
name = "market_data_relay"
path = "src/main.rs"
