#!/bin/bash
# AlphaPulse Cleanup Script
# Removes unneeded directories and files

echo "🧹 Starting AlphaPulse cleanup..."

# Build artifacts (will be regenerated)
echo "🗑️  Removing Rust build artifacts..."
if [ -d "rust-services/target" ]; then
    rm -rf rust-services/target/
    echo "   ✅ Removed rust-services/target/ (~200MB)"
fi

# Python cache files (will be regenerated)
echo "🗑️  Removing Python cache files..."
find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
find . -name "*.pyc" -delete 2>/dev/null || true
echo "   ✅ Removed __pycache__ directories"

# Coverage reports (regenerated on test runs)
if [ -d "backend/htmlcov" ]; then
    rm -rf backend/htmlcov/
    echo "   ✅ Removed backend/htmlcov/"
fi

if [ -f "backend/.coverage" ]; then
    rm backend/.coverage
    echo "   ✅ Removed backend/.coverage"
fi

# Test cache (regenerated by pytest)
if [ -d "backend/.pytest_cache" ]; then
    rm -rf backend/.pytest_cache/
    echo "   ✅ Removed backend/.pytest_cache/"
fi

# Frontend backups (old dated backups)
if [ -d "frontend/backups" ]; then
    rm -rf frontend/backups/
    echo "   ✅ Removed frontend/backups/"
fi

# Empty frontend directory
if [ -d "frontend/alphapulse-ui" ]; then
    if [ "$(find frontend/alphapulse-ui -type f | wc -l)" -eq 0 ]; then
        rm -rf frontend/alphapulse-ui/
        echo "   ✅ Removed empty frontend/alphapulse-ui/"
    else
        echo "   ⚠️  Skipped frontend/alphapulse-ui/ (contains files)"
    fi
fi

echo ""
echo "🤔 MANUAL REVIEW NEEDED:"
echo "   📁 archive_ap_legacy/ (~Large) - Legacy backup, likely safe to delete"
echo "      Contains: old app.py, test files, optimization results"
echo "      Command: rm -rf archive_ap_legacy/"
echo ""
echo "✅ Cleanup complete! Space saved: ~200MB+"
echo "   Build artifacts will regenerate automatically when needed."
