Development journal for AlphaPulse

High level goals:
- [ ] get UI functional, even if using dummy data and functions
- [ ] always maintain ability to connect to live seamlessly
- [ ] in UI, plan out for how to incorporate ML, stat arb and other non-TA / price action strategies 

** <2025-08-01 Fri>
Focus today is on abdoning ADMF-PC codebase, and starting fresh with a UI-first development approach.
*** TODO Get Oauth Working -- POSTPONED 
This was postponed due to the application process required with Alpaca. Best to wait until the app is more mature. 
*** DONE Get Live Data Streaming to Lightweight Charts
*** TODO Verify Live Data streams 
*** TODO Rename *-web and *-engine to suffix only 
*** TODO Create actual news feed / scraper and submission system, backend for storage, etc. 
*** TODO Plan out test driven development?
*** TODO Create step-through strategy thing to ensure desired behavior (bar by bar replay of strategy)
*** TODO Modify chart display to pull chart using strategy requirements? 
