[package]
name = "alphapulse-signal-relay"
version = "0.1.0"
edition = "2021"
description = "High-performance signal relay for trading strategies"

[dependencies]
# Core relay infrastructure with balanced features
alphapulse-relays = { path = "..", features = ["signal-relay"] }
protocol_v2 = { path = "../../protocol_v2" }

# Async runtime - minimal features for binary
tokio = { version = "1.0", features = ["rt-multi-thread", "net", "io-util", "time", "macros"] }
async-trait = "0.1"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Error handling
anyhow = "1.0"

# Command line
clap = { version = "4.0", features = ["derive"] }

# Utilities
bytes = "1.5"
futures = "0.3"

[[bin]]
name = "signal_relay"
path = "src/main.rs"
