[package]
name = "alphapulse-topology"
version = "0.1.0"
edition = "2021"
description = "Declarative topology system for AlphaPulse actor deployment"

[dependencies]
# Configuration and serialization
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Async runtime
tokio = { version = "1.40", features = ["full"] }
async-trait = "0.1"

# Collections and utilities
indexmap = "2.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
regex = "1.10"

# Protocol integration (when available)
# alphapulse-protocol-v2 = { path = "../protocol_v2" }

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# System-level operations
libc = "0.2"
nix = { version = "0.27", features = ["process", "sched"] }

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.0"
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.5"


[features]
default = []
protocol-integration = []  # Enable when protocol_v2 is ready
numa-optimization = []     # Enable NUMA-specific features