# AlphaPulse Development Environment Configuration

# Basic paths for development
socket_dir = "/tmp/alphapulse"
log_dir = "/tmp/alphapulse_logs"
pid_file = "/tmp/alphapulse_system.pids"

# Service-specific configurations
[services]

[services.market_data_relay]
enabled = true
health_port = 8001
priority = 10
# socket_path = "/tmp/alphapulse/market_data.sock"  # Default

[services.signal_relay]  
enabled = true
health_port = 8002
priority = 20
# socket_path = "/tmp/alphapulse/signals.sock"  # Default

[services.execution_relay]
enabled = true
health_port = 8003
priority = 30
# socket_path = "/tmp/alphapulse/execution.sock"  # Default

[services.polygon_publisher]
enabled = true
health_port = 8004
priority = 40

[services.flash_arbitrage]
enabled = true
health_port = 8005
priority = 50

[services.dashboard_websocket]
enabled = true
health_port = 8006
priority = 60

[services.kraken_collector]
enabled = false  # Optional for development
health_port = 8007
priority = 70

[services.binance_collector]
enabled = false  # Optional for development
health_port = 8008
priority = 80

[services.coinbase_collector]
enabled = false  # Optional for development
health_port = 8009
priority = 90