[package]
name = "alphapulse-adapter-service"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Exchange data collection and distribution adapters for AlphaPulse trading system"

[features]
default = []
strict-validation = []
metrics = ["prometheus"]

[[bin]]
name = "polygon"
path = "src/bin/polygon/polygon.rs"

[[bin]]
name = "binance"
path = "src/bin/binance/binance.rs"

[[bin]]
name = "kraken"
path = "src/bin/kraken/kraken.rs"

[[bin]]
name = "coinbase"
path = "src/bin/coinbase/coinbase.rs"

[[bin]]
name = "event_validator"
path = "src/bin/event_validator.rs"

[[bin]]
name = "test_semantic_equality" 
path = "../../test_semantic_equality.rs"

[[bin]]
name = "test_real_polygon_pipeline"
path = "../../test_real_polygon_pipeline.rs"

[[bin]]
name = "test_polygon_streaming"
path = "../../test_polygon_streaming.rs"

[[bin]]
name = "test_polygon_websocket"
path = "../../test_polygon_websocket.rs"

[[bin]]
name = "test_alternative_polygon_endpoints"
path = "../../test_alternative_polygon_endpoints.rs"

[[bin]]
name = "test_exact_subscription"
path = "../../test_exact_subscription.rs"

[[bin]]
name = "test_ethabi_events"
path = "../../test_ethabi_events.rs"

[[bin]]
name = "debug_subscription"
path = "../../debug_subscription.rs"

[[bin]]
name = "test_config_signatures"
path = "../../test_config_signatures.rs"

[[bin]]
name = "test_ethabi_subscription"
path = "../../test_ethabi_subscription.rs"

[[bin]]
name = "test_broader_subscription"
path = "../../test_broader_subscription.rs"

[[bin]]
name = "test_quicknode_polygon"
path = "../../test_quicknode_polygon.rs"

[[bin]]
name = "test_market_data_consumer"
path = "../../test_market_data_consumer.rs"

[[bin]]
name = "test_pool_cache_integration"
path = "../../test_pool_cache_integration_manual.rs"

[dependencies]
# Core protocol
protocol_v2 = { workspace = true }
alphapulse-state-market = { workspace = true }
alphapulse-dex = { workspace = true }
async-trait = { workspace = true }

# Async runtime
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }

# Error handling and logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }

# Utilities
hex = { workspace = true }
dashmap = { workspace = true }
clap = { version = "4.5", features = ["derive"] }
once_cell = { workspace = true }
rust_decimal = { workspace = true }
bytemuck = { workspace = true }
zerocopy = { workspace = true }

# HTTP client for REST fallbacks
reqwest = { workspace = true }
url = { workspace = true }

# Web3 and Ethereum
web3 = { workspace = true }
ethabi = { workspace = true }
lazy_static = "1.4"

# Rate limiting
governor = { workspace = true }
nonzero_ext = { workspace = true }

# Metrics
prometheus = { version = "0.13", optional = true }

# Pool cache persistence
memmap2 = { workspace = true }
crc32fast = { workspace = true }
crossbeam-channel = { workspace = true }

# Documentation enhancements
aquamarine = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"
mockito = "1.5"
criterion = "0.5"
tracing-subscriber = "0.3"
rand = "0.8"
rand_chacha = "0.3"
hex-literal = "0.4"
tempfile = "3.0"


[[bench]]
name = "message_processing"
harness = false