[package]
name = "alphapulse-kraken-signals"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]

# Protocol dependencies
alphapulse-types = { path = "../../../libs/types" }
anyhow = { workspace = true }

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Checksums
crc32fast = "1.3"

# Collections and concurrency
dashmap = "6.0"

# Metrics
metrics = "0.23"
parking_lot = "0.12"

# Math and calculations
rust_decimal = "1.32"
rust_decimal_macros = "1.32"
serde = { workspace = true }

# Error handling
thiserror = "1.0"
# Core dependencies
tokio = { workspace = true }

# Configuration
toml = "0.8"
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
