[package]
name = "alphapulse-transport"
version = "0.1.0"
edition = "2021"
description = "High-performance network transport system for AlphaPulse actor communication"

[dependencies]
# Core async runtime
tokio = { version = "1.40", features = ["full"] }
async-trait = "0.1"
futures = "0.3"

# Networking
mio = "0.8"
quinn = { version = "0.10", optional = true }  # QUIC implementation
socket2 = "0.5"                   # Low-level socket control

# Serialization and configuration
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
bincode = "1.3"                   # Fast binary serialization
byteorder = "1.5"                 # Byte order utilities for network protocols

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Compression
lz4 = { version = "1.24", optional = true }  # Fast compression
zstd = { version = "0.13", optional = true } # Better compression ratio
snap = { version = "1.1", optional = true }  # Google Snappy

# Encryption and security
rustls = { version = "0.21", optional = true }  # TLS implementation
rustls-native-certs = { version = "0.6", optional = true }  # Native certificate loading
chacha20poly1305 = { version = "0.10", optional = true }  # Fast authenticated encryption
ring = { version = "0.17", optional = true }  # Cryptographic primitives

# Message Queues (optional features)
lapin = { version = "2.3", optional = true }       # RabbitMQ client
rdkafka = { version = "0.33", optional = true }    # Kafka client
redis = { version = "0.23", optional = true }      # Redis client

# Collections and utilities
indexmap = "2.0"
uuid = { version = "1.0", features = ["v4"] }
parking_lot = "0.12"              # Fast synchronization primitives
dashmap = "5.0"                   # Concurrent hashmap
rand = "0.8"                      # Random number generation

# Monitoring and observability
prometheus = { version = "0.13", optional = true }
tracing = "0.1"
tracing-subscriber = "0.3"
metrics = { version = "0.21", optional = true }

# System-level operations
nix = { version = "0.27", features = ["socket", "net"] }
libc = "0.2"

# Integration with other AlphaPulse modules
alphapulse-topology = { path = "../topology" }
# alphapulse-protocol-v2 = { path = "../protocol_v2" }  # Will be enabled later

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.0"
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.5"
wiremock = "0.5"                  # Mock HTTP servers for testing

[features]
default = ["tcp", "udp", "compression", "encryption"]

# Transport protocols
tcp = []
udp = []
quic = ["quinn"]

# Optimization features
compression = ["lz4", "zstd", "snap"]
encryption = ["rustls", "rustls-native-certs", "chacha20poly1305", "ring"]

# Message queue backends
rabbitmq = ["lapin"]
kafka = ["rdkafka"]
redis-mq = ["redis"]
message-queues = ["rabbitmq", "kafka", "redis-mq"]

# Monitoring and metrics
monitoring = ["prometheus", "metrics"]

# Development and testing features
dev-tools = []

[[bench]]
name = "latency"
harness = false

# [[bench]]
# name = "throughput"
# harness = false

# [[bench]]
# name = "comparison"
# harness = false