[package]
name = "trace_collector"
version = "0.1.0"
edition = "2021"

[dependencies]
# Protocol
protocol_v2 = { workspace = true }

# Async runtime
tokio = { version = "1.0", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling and logging
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
thiserror = "1.0"

# Networking
url = "2.0"

# Collections and sync
dashmap = "5.0"
parking_lot = "0.12"

# Ring buffer
ringbuffer = "0.15"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# System info
sysinfo = "0.30"

# Hex encoding
hex = "0.4"

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.0"